using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using java.io;
using java.util;

using edu.stanford.nlp.ling;
using edu.stanford.nlp.process;
using edu.stanford.nlp.objectbank;
using edu.stanford.nlp.tagger.maxent;

namespace StanfordPOSTagger.Csharp.Samples
{
    // This demo shows user-provided sentences (i.e., {@code List<HasWord>})
    //  being tagged by the tagger. The sentences are generated by direct use
    //  of the DocumentPreprocessor class.
    //
    //  @author Christopher Manning
    public static class TaggerDemo2
    {
        public static void Execute(string fileName)
        {
            var tagger = new MaxentTagger(TaggerDemo.Model);
            var ptbTokenizerFactory = PTBTokenizer.factory(new CoreLabelTokenFactory(), "untokenizable=noneKeep");
            var r = new BufferedReader(new InputStreamReader(new FileInputStream(fileName), "utf-8"));
            var documentPreprocessor = new DocumentPreprocessor(r);
            documentPreprocessor.setTokenizerFactory(ptbTokenizerFactory);
            foreach (List sentence in documentPreprocessor)
            {
                var tSentence = tagger.tagSentence(sentence);
                System.Console.WriteLine(Sentence.listToString(tSentence, false));
            }
        }
    }
}
