module TaggerDemo2

open java.io
open java.util

open edu.stanford.nlp.ling
open edu.stanford.nlp.``process``
open edu.stanford.nlp.objectbank
open edu.stanford.nlp.tagger.maxent

// This demo shows user-provided sentences (i.e., {@code List<HasWord>})
//  being tagged by the tagger. The sentences are generated by direct use
//  of the DocumentPreprocessor class.
//
//  @author Christopher Manning

let model = @"..\..\..\..\temp\stanford-postagger-2013-06-20\models\wsj-0-18-bidirectional-nodistsim.tagger"

let main (fileName:string) = 
    let tagger = MaxentTagger(model)
    let ptbTokenizerFactory = PTBTokenizer.factory(CoreLabelTokenFactory(), "untokenizable=noneKeep")
    let r = new BufferedReader(new InputStreamReader(new FileInputStream(fileName), "utf-8"))
    let documentPreprocessor = new DocumentPreprocessor(r)
    documentPreprocessor.setTokenizerFactory(ptbTokenizerFactory)
    documentPreprocessor
    |> Iterable.toSeq
    |> Seq.iter (fun sentence ->
        let tSentence = tagger.tagSentence(sentence :?> List)
        printfn "%O" (Sentence.listToString(tSentence, false))
        )